pipeline {
    agent any

    environment {
        SONARQUBE_URL = 'http://54.160.35.37:9000'
        SONARQUBE_TOKEN = credentials('sonarqube-token') // Store this in Jenkins credentials
        NEXUS_URL = 'http://23.22.104.243:8081'  // Update with your Nexus server URL
        NEXUS_REPO = 'maven-releases'  // Update with your Nexus repository name
        NEXUS_CREDENTIALS_ID = 'nexus-credentials' // Store Nexus username/password in Jenkins credentials
        TOMCAT_URL = 'http://54.234.205.18:8080' // Update with your Tomcat server URL
        TOMCAT_CREDENTIALS_ID = 'tomcat-credentials' // Store Tomcat username/password in Jenkins credentials
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/saurabhshende13/Test.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    sh '''
                    mvn sonar:sonar \
                        -Dsonar.projectKey=java-app \
                        -Dsonar.host.url=${SONARQUBE_URL} \
                        -Dsonar.login=${SONARQUBE_TOKEN}
                    '''
                }
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package -DskipTests'
            }
        }

        stage('Upload Artifact to Nexus') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'nexus-credentials', usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                        sh '''
                        mvn deploy:deploy-file \
                            -DgroupId=com.example \
                            -DartifactId=ci-cd-tomcat-project \
                            -Dversion=1.0.5 \
                            -Dpackaging=war \
                            -Dfile=target/ci-cd-tomcat-project-1.0-SNAPSHOT.war \
                            -DrepositoryId=nexus \
                            -Durl=${NEXUS_URL}/repository/${NEXUS_REPO}/ \
                            -Dusername=$NEXUS_USER \
                            -Dpassword=$NEXUS_PASS
                        '''
                    }
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'tomcat-credentials', usernameVariable: 'TOMCAT_USER', passwordVariable: 'TOMCAT_PASS')]) {
                        sh '''
                        curl -v -u $TOMCAT_USER:$TOMCAT_PASS -T target/ci-cd-tomcat-project-1.0-SNAPSHOT.war \
                        ${TOMCAT_URL}/manager/text/deploy?path=/ci-cd-tomcat-project&update=true
                        '''
                    }
                }
            }
        }
    }
}