name: ci-cd-dev

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    name: Build → Push → Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://34.201.136.252:9000"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/myntra-app:latest .
          docker push ${{ secrets.DOCKERHUB_USER }}/myntra-app:latest
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via SSM to EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --comment "Deploy Docker container from GitHub Actions" \
            --parameters commands="docker pull ${{ secrets.DOCKERHUB_USER }}/myntra-app:latest && docker stop myntra-app || true && docker rm myntra-app || true && docker run -d --name myntra-app -p 3000:3000 ${{ secrets.DOCKERHUB_USER }}/myntra-app:latest" \
            --output text


