name: ci-cd-dev

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  ENVIRONMENT: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://34.201.136.252:9000"
